config/routes.rb
Restate::Application.routes.draw do
 
  resources :properties

  devise_for :users

  devise_for :admins
  
  resource :admin, :controller => "Admin::Main"
  
  namespace :admin do
    resources :features, :controller
    resources :properties do
      resources :features
    end    
  end

  root :to => "welcome#index"

end

app/models/property_feature.rb
class PropertyFeature < ActiveRecord::Base
  belongs_to :property
  belongs_to :feature
end

app/controllers/admin/property_features_controller.rb
class Admin::PropertyFeaturesController < Admin::MainController
  # GET /property_features
  # GET /property_features.xml
  def index
    @property_features = PropertyFeature.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @property_features }
    end
  end

  # GET /property_features/1
  # GET /property_features/1.xml
  def show
    @property_feature = PropertyFeature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @property_feature }
    end
  end

  # GET /property_features/new
  # GET /property_features/new.xml
  def new
    @property_feature = PropertyFeature.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @property_feature }
    end
  end

  # GET /property_features/1/edit
  def edit
    @property_feature = PropertyFeature.find(params[:id])
  end

  # POST /property_features
  # POST /property_features.xml
  def create
    @property_feature = PropertyFeature.new(params[:property_feature])

    respond_to do |format|
      if @property_feature.save
        format.html { redirect_to(@property_feature, :notice => 'Property feature was successfully created.') }
        format.xml  { render :xml => @property_feature, :status => :created, :location => @property_feature }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @property_feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /property_features/1
  # PUT /property_features/1.xml
  def update
    @property_feature = PropertyFeature.find(params[:id])

    respond_to do |format|
      if @property_feature.update_attributes(params[:property_feature])
        format.html { redirect_to(@property_feature, :notice => 'Property feature was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @property_feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /property_features/1
  # DELETE /property_features/1.xml
  def destroy
    @property_feature = PropertyFeature.find(params[:id])
    @property_feature.destroy

    respond_to do |format|
      format.html { redirect_to(property_features_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/property_features_controller.rb
class PropertyFeaturesController < ApplicationController
  # GET /property_features
  # GET /property_features.xml
  def index
    @property_features = PropertyFeature.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @property_features }
    end
  end

  # GET /property_features/1
  # GET /property_features/1.xml
  def show
    @property_feature = PropertyFeature.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @property_feature }
    end
  end

  # GET /property_features/new
  # GET /property_features/new.xml
  def new
    @property_feature = PropertyFeature.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @property_feature }
    end
  end

  # GET /property_features/1/edit
  def edit
    @property_feature = PropertyFeature.find(params[:id])
  end

  # POST /property_features
  # POST /property_features.xml
  def create
    @property_feature = PropertyFeature.new(params[:property_feature])

    respond_to do |format|
      if @property_feature.save
        format.html { redirect_to(@property_feature, :notice => 'Property feature was successfully created.') }
        format.xml  { render :xml => @property_feature, :status => :created, :location => @property_feature }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @property_feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /property_features/1
  # PUT /property_features/1.xml
  def update
    @property_feature = PropertyFeature.find(params[:id])

    respond_to do |format|
      if @property_feature.update_attributes(params[:property_feature])
        format.html { redirect_to(@property_feature, :notice => 'Property feature was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @property_feature.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /property_features/1
  # DELETE /property_features/1.xml
  def destroy
    @property_feature = PropertyFeature.find(params[:id])
    @property_feature.destroy

    respond_to do |format|
      format.html { redirect_to(property_features_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/property_features_helper.rb
module PropertyFeaturesHelper
end

app/views/admin/property_features/_form.html.erb
<%= form_for(@property_feature) do |f| %>
  <% if @property_feature.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property_feature.errors.count, "error") %> prohibited this property_feature from being saved:</h2>

      <ul>
      <% @property_feature.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :value %><br />
    <%= f.text_field :value %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :property %><br />
    <%= f.text_field :property %>
  </div>
  <div class="field">
    <%= f.label :feature %><br />
    <%= f.text_field :feature %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/property_features/edit.html.erb
<h1>Editing property_feature</h1>

<%= render 'form' %>

<%= link_to 'Show', @property_feature %> |
<%= link_to 'Back', property_features_path %>

app/views/admin/property_features/index.html.erb
<h1>Listing property_features</h1>

<table>
  <tr>
    <th>Value</th>
    <th>Description</th>
    <th>Property</th>
    <th>Feature</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @property_features.each do |property_feature| %>
  <tr>
    <td><%= property_feature.value %></td>
    <td><%= property_feature.description %></td>
    <td><%= property_feature.property %></td>
    <td><%= property_feature.feature %></td>
    <td><%= link_to 'Show', property_feature %></td>
    <td><%= link_to 'Edit', edit_property_feature_path(property_feature) %></td>
    <td><%= link_to 'Destroy', property_feature, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property feature', new_property_feature_path %>

app/views/admin/property_features/new.html.erb
<h1>New property_feature</h1>

<%= render 'form' %>

<%= link_to 'Back', property_features_path %>

app/views/admin/property_features/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Value:</b>
  <%= @property_feature.value %>
</p>

<p>
  <b>Description:</b>
  <%= @property_feature.description %>
</p>

<p>
  <b>Property:</b>
  <%= @property_feature.property %>
</p>

<p>
  <b>Feature:</b>
  <%= @property_feature.feature %>
</p>


<%= link_to 'Edit', edit_property_feature_path(@property_feature) %> |
<%= link_to 'Back', property_features_path %>