config/routes.rb
Restate::Application.routes.draw do
 
  resources :properties

  devise_for :users

  devise_for :admins
  
  resource :admin, :controller => "Admin::Main"
  
  namespace :admin do
    resources :features, :controller
    resources :properties do
      resources :features
    end    
  end

  root :to => "welcome#index"

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  belongs_to :property_type
  has_many :property_photos
  
  accepts_nested_attributes_for :property_photos
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < Admin::MainController
  
  def index
    @properties = Property.paginate :all, :page => params[:page], :per_page => 50
  end
  
  def new
    @property = Property.new
    @property.property_photos.build
  end
  
  def create
    @property = Property.new(params[:property])
    if @property.save
      flash[:notice] = "Property saved successfully"
      redirect_to admin_properties_path
    else
      render :action => :new
    end
  end
  
  def destroy
    @property = Property.find(params[:id])
    if @property.destroy
      flash[:notice] = "Property has been lost"
    else
      flash[:error] = "YOU SHALL NOT PASS!!"
    end
    redirect_to admin_properties_path
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.xml
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.xml
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.xml
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.xml
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to(@property, :notice => 'Property was successfully created.') }
        format.xml  { render :xml => @property, :status => :created, :location => @property }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.xml
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to(@property, :notice => 'Property was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.xml
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to(properties_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_for(@property) do |f| %>
  <% if @property.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
      <% @property.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :property_type %><br />
    <%= f.text_field :property_type %>
  </div>
  <div class="field">
    <%= f.label :date_on_market %><br />
    <%= f.date_select :date_on_market %>
  </div>
  <div class="field">
    <%= f.label :date_off_market %><br />
    <%= f.date_select :date_off_market %>
  </div>
  <div class="field">
    <%= f.label :property_name %><br />
    <%= f.text_field :property_name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :garage %><br />
    <%= f.check_box :garage %>
  </div>
  <div class="field">
    <%= f.label :parking %><br />
    <%= f.check_box :parking %>
  </div>
  <div class="field">
    <%= f.label :room_count %><br />
    <%= f.text_field :room_count %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :price_min %><br />
    <%= f.text_field :price_min %>
  </div>
  <div class="field">
    <%= f.label :price_max %><br />
    <%= f.text_field :price_max %>
  </div>
  <div class="field">
    <%= f.label :other_details %><br />
    <%= f.text_area :other_details %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render 'form' %>

<%= link_to 'Show', @property %> |
<%= link_to 'Back', properties_path %>

app/views/properties/index.html.erb
<h1>Listing properties</h1>

<table>
  <tr>
    <th>User</th>
    <th>Property type</th>
    <th>Date on market</th>
    <th>Date off market</th>
    <th>Property name</th>
    <th>Property description</th>
    <th>Garage</th>
    <th>Parking</th>
    <th>Room count</th>
    <th>Price</th>
    <th>Price min</th>
    <th>Price max</th>
    <th>Other property details</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @properties.each do |property| %>
  <tr>
    <td><%= property.user %></td>
    <td><%= property.property_type %></td>
    <td><%= property.date_on_market %></td>
    <td><%= property.date_off_market %></td>
    <td><%= property.property_name %></td>
    <td><%= property.property_description %></td>
    <td><%= property.garage %></td>
    <td><%= property.parking %></td>
    <td><%= property.room_count %></td>
    <td><%= property.price %></td>
    <td><%= property.price_min %></td>
    <td><%= property.price_max %></td>
    <td><%= property.other_property_details %></td>
    <td><%= link_to 'Show', property %></td>
    <td><%= link_to 'Edit', edit_property_path(property) %></td>
    <td><%= link_to 'Destroy', property, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Property', new_property_path %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render 'form' %>

<%= link_to 'Back', properties_path %>

app/views/properties/show.html.erb
<p id="notice"><%= notice %></p>

<% @property.property_photos.each do |photo| %>
  <%= image_tag photo.photo.url %>
<% end %>

<p>
  <b>User:</b>
  <%= @property.user %>
</p>

<p>
  <b>Property type:</b>
  <%= @property.property_type %>
</p>

<p>
  <b>Date on market:</b>
  <%= @property.date_on_market %>
</p>

<p>
  <b>Date off market:</b>
  <%= @property.date_off_market %>
</p>

<p>
  <b>Property name:</b>
  <%= @property.name %>
</p>

<p>
  <b>Property description:</b>
  <%= @property.description %>
</p>

<p>
  <b>Garage:</b>
  <%= @property.garage %>
</p>

<p>
  <b>Parking:</b>
  <%= @property.parking %>
</p>

<p>
  <b>Room count:</b>
  <%= @property.room_count %>
</p>

<p>
  <b>Price:</b>
  <%= @property.price %>
</p>

<p>
  <b>Price min:</b>
  <%= @property.price_min %>
</p>

<p>
  <b>Price max:</b>
  <%= @property.price_max %>
</p>

<p>
  <b>Other property details:</b>
  <%= @property.other_details %>
</p>


<%= link_to 'Edit', edit_property_path(@property) %> |
<%= link_to 'Back', properties_path %>