config/routes.rb
Restate::Application.routes.draw do
 
  resources :properties

  devise_for :users

  devise_for :admins
  
  resource :admin, :controller => "Admin::Main"
  
  namespace :admin do
    resources :features, :controller
    resources :properties do
      resources :features
    end    
  end

  root :to => "welcome#index"

end

app/models/property.rb
class Property < ActiveRecord::Base
  belongs_to :user
  belongs_to :property_type
  has_many :property_photos
  
  accepts_nested_attributes_for :property_photos
end

app/models/property_type.rb
class PropertyType < ActiveRecord::Base
end

app/controllers/admin/properties_controller.rb
class Admin::PropertiesController < Admin::MainController
  
  def index
    @properties = Property.paginate :all, :page => params[:page], :per_page => 50
  end
  
  def new
    @property = Property.new
    @property.property_photos.build
  end
  
  def create
    @property = Property.new(params[:property])
    if @property.save
      flash[:notice] = "Property saved successfully"
      redirect_to admin_properties_path
    else
      render :action => :new
    end
  end
  
  def destroy
    @property = Property.find(params[:id])
    if @property.destroy
      flash[:notice] = "Property has been lost"
    else
      flash[:error] = "YOU SHALL NOT PASS!!"
    end
    redirect_to admin_properties_path
  end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  # GET /properties
  # GET /properties.xml
  def index
    @properties = Property.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @properties }
    end
  end

  # GET /properties/1
  # GET /properties/1.xml
  def show
    @property = Property.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @property }
    end
  end

  # GET /properties/new
  # GET /properties/new.xml
  def new
    @property = Property.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @property }
    end
  end

  # GET /properties/1/edit
  def edit
    @property = Property.find(params[:id])
  end

  # POST /properties
  # POST /properties.xml
  def create
    @property = Property.new(params[:property])

    respond_to do |format|
      if @property.save
        format.html { redirect_to(@property, :notice => 'Property was successfully created.') }
        format.xml  { render :xml => @property, :status => :created, :location => @property }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /properties/1
  # PUT /properties/1.xml
  def update
    @property = Property.find(params[:id])

    respond_to do |format|
      if @property.update_attributes(params[:property])
        format.html { redirect_to(@property, :notice => 'Property was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @property.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1
  # DELETE /properties/1.xml
  def destroy
    @property = Property.find(params[:id])
    @property.destroy

    respond_to do |format|
      format.html { redirect_to(properties_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/admin/properties/_form.html.haml
= semantic_form_for @property, :url => admin_properties_path, :html => {:multipart => true}  do |form|
  = form.inputs
  
  = form.semantic_fields_for :property_photos do |property_photo|
    = property_photo.input :photo, :as => :file
    
  = form.buttons do
    = form.commit_button
    
    

app/views/admin/properties/index.html.haml
%h1 Recent Properties

%table{:border => "1px solid black"}
  %tr
    %th ID
    %th Name
    %th Type
    %th &nbsp;
    
  - @properties.each do |property|
    %tr
      %td= property.id
      %td= property.name
      %td= property.description
      %td
        = link_to("Edit", edit_admin_property_path(property))
        |
        = link_to 'Destroy', admin_property_path(property), :confirm => 'Are you sure?', :method => :delete
        
%p
  = link_to("Add a Property", new_admin_property_path)
  
= will_paginate @properties

app/views/admin/properties/new.html.haml
%h1 Add a property

= error_messages_for :property

= render :partial => 'form'
    
    
  