config/routes.rb
Restate::Application.routes.draw do
 
  resources :properties

  devise_for :users

  devise_for :admins
  
  resource :admin, :controller => "Admin::Main"
  
  namespace :admin do
    resources :features, :controller
    resources :properties do
      resources :features
    end    
  end

  root :to => "welcome#index"

end

app/views/layouts/admin.html.haml
!!!

%html{:xmlns => "http://www.w3.org/1999/xhtml", "xml:lang" => "en", :lang => "en"}
  %head
    %title
      Administration - Restate.ph
   
    = stylesheet_link_tag 'admin.css', 'formtastic.css', 'formtastic_changes.css', :media => 'screen, print'
    = javascript_include_tag :all
   

  %body
    #container
      #header
        .title 
          Restate Admin
        .links
          - if admin_signed_in?
            %strong= current_admin.email
            |
            =  link_to("Sign Out", destroy_admin_session_path)
    
      #navigation
        %ul
          %li= link_to_unless_current "Home", admin_path
          %li= link_to_unless_current "Features", admin_features_path
          %li.last= link_to_unless_current "Properties", admin_properties_path
            
      = render :partial => 'shared/flash_messages'
      = yield

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Restate</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
<div>
  HEADER IMAGE HEREs
</div>
<hr>
SPACER
<hr>
SEARCH
<hr>
<%= yield %>
<hr>
FOOTER
<hr>
</body>
</html>